### ISSUE TITLE
ДЗ2 - 1. Індексований масив замінити на асоціативний

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#1]
Математично все вірно і працює як треба, але є претензії/побажання до структури коду.
Перше з чого треба почати - змінити тип збереження даних. Ти використовуєш звичайний масив, але набагато доцільніше використовувати асоціативний масив, щоб це були не просто цифри - а ключі з значеннями. Бо зараз в коді легко загубитися в 0 та 1 (а якщо даних буде більше...). Тут є 2 варіанти:
```PHP
[
   [
      "amount": 10,
      "value": 1000
    ],
    ...
]
```

```PHP
[
    1000 => 10,
    ...
]
```

Я особисто віддаю перевагу 2 варіанту, але вимагає більш глибокого розуміння роботи з масивами (не всі функції працюють з ключами масивів), але залишаю вибір тобі.

https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data.json#L1-L10

ПС: Інші зауваження вже напишу завтра, в такому ж форматі - опис + посилання на код якого стосуються, окремими повідомленнями. Коли виправиш таке зауваження - його можна закрити (змінити статус) і мені тоді буде видно що ти їх опрацював (навіть нагадування прийде).

**Comment by Ihor986** [comment]
+ іду далі
