### ISSUE TITLE
ДЗ3 - 2. Все трохи складніше

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#11]
У 4 завданні сказано:

4. Складіть запит для отримання усіх користувачів, на рахунку яких більше 1000 (незалежно від валюти), до результату додати цей баланс

І тут мається на увазі, що треба вивести користувачів (це в тебе є), об'єднати з акантами та згрупувати за користувачами з сумуванням балансів, та додати фільтр на знайдений баланс (більше 1000). І вивести дані користувача та сумарний баланс по усіх рахунках незалежно від валюти.

https://github.com/Ihor986/homeWork/blob/20070ede459843f96e38efdf394bc66d533d3d80/dz3/list%20of%20homework%20requests.txt#L10

**Comment by Ihor986** [comment]
SELECT users.name, SUM(accounts.balance) FROM `users` JOIN accounts ON users.id=accounts.user_id GROUP BY users.name HAVING SUM(accounts.balance) > 1000;
