### ISSUE TITLE
ДЗ1 - 1. Невірний запис масива

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#2]
Відразу видно Джавіста (принаймні там так пишуть). При оголошенні та використанні треба екранувати ключі масивів одинарними чи подвійними лапками
```PHP
$arr = ['key' => 'value'];
$arr2 = ["key" => "value"];
$arr["key"] = 12;
$var = $arr2['key'];
```
При дефолтних налаштуваннях ОпенСервера мені кидає купу попереджень про невідомі константи і приводить їх до стрінга (без долара у ПХП лише константи пишуться), і попереджає що у майбутніх версіях це перетворення приберуть.

ПС:
Це ж стосується і 2 ДЗ, там теж зустрічається така помилка.

https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz1/index.php#L14-L33

**Comment by Ihor986** [comment]
+
