### ISSUE TITLE
ДЗ1 - 2. Недоліки структури

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#3]
1. У тебе розрахунок робиться двічі ідентичною функцією (вони мать робилися з однієї), тож хай це буде одна функція. Але вона може повертати асоціативний масив з сумою та терміном.
2. Не треба у функціях писати у потік (команди ехо). функція рахує і все.
3. Використання параметра "і" понижує розуміння коду, давай зрозумілі назви змінним

https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz1/index.php#L35-L50
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz1/index.php#L52-L67

**Comment by Ihor986** [comment]
+
