### ISSUE TITLE
ДЗ1 - 3. Зауваження до універсальності

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#4]
У кінці файлу ти створюєш 6 змінних і ніде їх не використовуєш... Але я ще говорив про можливість розширення. Ти створив масив з банками - вірне рішення, але при такому виводі інформації (ручний виклик функцій) при доданні ще одного в масив треба буде і код правити. Тут треба зробити перебір елементів масиву банків циклом. У циклі ти отримуєш результат обрахунку і виводиш користувачу (тоді формат виводу буде однаковий і не буде дублювання коду). При бажанні - можна винести вивід інформації по розрахунку банку у окрему функцію.
**Поки що це всі зауваження до першого завдання.**

https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz1/index.php#L68-L74

**Comment by Ihor986** [comment]
+ ніби все, сподіваюся нових зауважень буде менше))
