### ISSUE TITLE
ДЗ2 - 2. Дублювання коду при виводі помилок

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#5]
У тебе всі помилки однотипні, от і використай функцію для них (для виводу помилки та завершення програми). Перший шматок коду теж можна об'єднати у функцію як початкову перевірку. 
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data-insert.php#L20-L36
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data-insert.php#L64-L68

**Comment by Ihor986** [comment]
+
