### ISSUE TITLE
ДЗ2 - 3. Просунуте використання функцій масивів

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#6]
Є претензія до назви функції, якщо вона знаходить суму банкнот - то можна назвати "findMoneySumm()".
В даному контексті підійшла б функція "array_reduce()", про яку я розповідав. Спробуй переписати.
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data-insert.php#L10-L16

**Comment by Ihor986** [comment]
+
