### ISSUE TITLE
ДЗ2 - 4. Зайвий код

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#7]
Не розумію призначення цього присвоєння, навіщо тобі пустий масив. адже в циклі ти потім його заповнюєш у кожній ітерації, де в тебе є дані скільки банкнот ти взяв і якого номіналу. Оголосити змінну треба, щоб вона була глобальною, але можна просто присвоїти пустий масив "[]".
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data-insert.php#L38-L47

**Comment by Ihor986** [comment]
+
