### ISSUE TITLE
ДЗ2 - 5. Вимоги по якості коду

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#8]
Тут ти перевіряєш чи число кратне доволі дивним способом. Далі ти ж використовуєш функцію знаходження залишку від ділення "%" тож тут теж було б оптимально її використати. Якщо залишок "0" - все добре...
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data-insert.php#L32

Кнопку повернення можна просто вивести у кінці сторінки, щоб вона виводилась останньою, а не в функції. Також використання функції "exit()" не рекомендую. Краще додай якісь умови щоб якась частину коду пропускалась (if/else) і програма йшла до кінця (бо далі може виводитись ще купа інфи для виводу помилки у читабельному вигляді у повноцінних сайтах).
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data-insert.php#L22

Частину з генеруванням повідомлення про використані купюри для видачі краще винести у окрему функцію, яка буде приймати масив використаних купюр після усіх перевірок (щоб не виконувати зайві операції)
https://github.com/Ihor986/homeWork/blob/e5b90358eec625a2c0ce2679f90964932b00f3db/dz2/data-insert.php#L59-L61

Також пиши функції підряд, а код який їх викликає окремо, тоді воно зрозуміліше!

**Ніби поки це всі зауваження, далі подивимось як ти їх виправиш. ;)**

**Comment by Ihor986** [comment]
+
