### ISSUE TITLE
Повторна перевірка.

### ISSUE THREAD

**Issue by amaneshi** [Ihor986/homeWork#9]
Цього разу обидва завдання набагато краще, молодець. Єдине що - краще формуй назви змінних, аби вони відображали їх вміст. Тоді код набагато легше читати.

Ти ще цікавився чи є ще завдання... Якщо є бажання то [тут](https://docs.google.com/document/d/176o35NmFbbR5hIMKV_f2Scxa_r6DkS5za6kZ3lNn9G8/edit?usp=sharing) є ще пара завдань (там їх 3, але 2 вже було).

**Comment by Ihor986** [comment]
Вийшло якось так - https://github.com/Ihor986/homeWork/tree/master/dz(plus)/verse  . Функції чи цикли вирішив не використовувати, так як виходило більше коду при тому ж результаті. Чи все рівно краще писати з застосуванням функцій?

**Comment by Ihor986** [comment]
> Цього разу обидва завдання набагато краще, молодець. Єдине що - краще формуй назви змінних, аби вони відображали їх вміст. Тоді код набагато легше читати.
> 
> Ти ще цікавився чи є ще завдання ... Якщо є бажання то [тут](https://docs.google.com/document/d/176o35NmFbbR5hIMKV_f2Scxa_r6DkS5za6kZ3lNn9G8/edit?usp=sharing) є ще пара завдань (там їх 3, але 2 вже було).

Вийшло якось так - https://github.com/Ihor986/homeWork/tree/master/dz(plus)/verse . Функції чи цикли вирішив не використовувати, так як виходило більше коду при тому ж результаті. Чи все рівно краще писати з застосуванням функцій?

**Comment by amaneshi** [comment]
В цьому випадку не обов'язково. Програма працює, поки цього достатньо. 3-тя задача має бути складнішою...

**Comment by Ihor986** [comment]
> В цьому випадку не обов'язково. Програма працює, поки цього достатньо. 3-тя задача має бути складнішою...

 3-тя задача була складнішою... сподіваюся незабагато костилів використав))

**Comment by Ihor986** [comment]
dz(plus)/shevchenko/index.php
